services:
  postgres:
    image: postgres:15
    container_name: employee_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: employeedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: employee_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/employeedb
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: